[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# Temporarily disabled - requires Deno installation
# [[edge_functions]]
#   function = "cors"
#   path = "/api/*"

[[scheduled.functions]]
  name = "cache-refresh"
  cron = "0 */6 * * *" # every 6 hours

[dev]
  command = "npm run dev"   # start Vite
  targetPort = 5173          # reuse Vite server
  port = 8888                # Netlify Dev proxy port
  autoLaunch = false
